### ISSUE TITLE
Search bar has no background color

### ISSUE THREAD

**Issue by 0xdeadc0d3** [ranmaru22/firefox-vertical-tabs#106]
Commit https://github.com/ranmaru22/firefox-vertical-tabs/pull/103/commits/08d6b39453097e156d9a7a228fcb557627230f43 broke background color of search bar 
![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/85187695/9a53d2a4-0515-493f-8bbb-df149b85d1af)

**Comment by YMSTNT** [comment]
This still happens when Dark or Light theme is used. When System theme - auto is used, it uses the GTK colors, which is fine.

Dark:
![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/21342713/e35e6250-80cd-49a9-86c7-65661270693c)
Light:
![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/21342713/066426d8-b480-4cb7-a56a-13e71415b040)
System theme - auto:
![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/21342713/e2c34b82-7a20-4202-aa5c-d942f7253cbe)

**Comment by ranmaru22** [comment]
Interesting. I can't reproduce this, so it seems like an issue with your GTK theme.

Could you try removing or commenting out the following lines from `userChrome.css` (33-36) and see if that fixes it?

```css
.browser-toolbar:not(.titlebar-color){ /* Fixes wrong coloring applied with --toolbar-bgcolor by Firefox (#101) */
        background-color: transparent !important;
        box-shadow: none !important;
    }
```

This is the only place we touch any coloring of the toolbar/titlebar at all, at least in Linux. There are some other CSS settings in the Windows section, but they should have no impact at all.

But it's still super weird that it behaves differently between the Dark and System (Dark) themes, which, for all I know, use the same color variables.
