### ISSUE TITLE
It's too easy to close a tab by mistake

### ISSUE THREAD

**Issue by akwodkiewicz** [ranmaru22/firefox-vertical-tabs#12]
When I quickly move your cursor to the left and click on the tab, I close the tab almost every time. It's not ergonomic to move your mouse/finger to the left, then wait for the animation to expand the tabs and then slightly to the right (to avoid the "X" button).

Maybe you could explore showing the "X" button **on the right side** of the label?
Or have an option to hide the "X" button?

**Comment by akwodkiewicz** [comment]
This is the modification that I'm using currently:

```css

/* Move close button to left side */
.tab-close {
    right: 0;
}

/* Fix title gradient */
#tablist .tab:hover > .tab-title-wrapper {
    mask-image: linear-gradient(to left, transparent 0, black 2em);
}

/* Move tab text to right when hovering to accomodate for the close button */
#tablist .tab:hover > .tab-title-wrapper {
    margin-right: 25px;
}
```

And this is the original snippet:

https://github.com/ranmaru22/firefox-vertical-tabs/blob/a5aa5604fd6a219a68ffcbe9387ce46172060c9a/tabCenterReborn.css#L126-L147
