### ISSUE TITLE
I can not get the tabs on the left to align like on the example screenshot, neatly with just a website's logo in the middle.

### ISSUE THREAD

**Issue by maxnersting** [ranmaru22/firefox-vertical-tabs#124]
https://imgtr.ee/image/bV2I2

**Comment by maxnersting** [comment]
There is probably some CSS or something that I have missed. I am not very good at this stuff.

**Comment by ranmaru22** [comment]
This seems like the set width of your sidebar is wrong. Have you made any changes?

The CSS lines which control this are these, lines 269-286 in userChrome.css.

```css
[sidebarcommand*="tabcenter"] #sidebar,
#sidebar-box[sidebarcommand*="tabcenter"] {
    min-width: 48px !important;
    max-width: 48px !important;
    width: 48px;
}

#sidebar-box[sidebarcommand*="tabcenter"]:not([hidden]) {
    display: block;
    position: var(--positionX2);
    min-width: 48px;
    max-width: 48px;
    overflow: hidden;
    border-right: 1px solid var(--sidebar-border-color);
    z-index: 1;
    top: 0;
    bottom: 0;
}
```

The 48px is the width the sidebar should have. If you've changed anything there, it could lead to your issue. Otherwise check whether you've followed the setup steps described in the Readme. I can't rule out that some TCR setting is causing this.

**Comment by maxnersting** [comment]
I have not changed anything, and I think I have followed the instructions correctly. Everything else works, at least.

**Comment by maxnersting** [comment]
I finally got my brother to use Firefix, but he has the same issue, despite him having changed or done nothing with his Firefox or TCR.

**Comment by ranmaru22** [comment]
I just did a clean install on my Firefox and now I can reproduce this.

It seems that `#sidebar` has become an inline element now and does not respect width settings anymore. When you force it back into block mode by using `display: block` it seems to work as before.

Weird is that it didn't happen on my old installation, despite being the same version number.

Anyway, I'll push a fix for this in a second.

**Comment by ranmaru22** [comment]
I'm keeping this issue open for now, could you or anyone else experiencing this issue confirm the fix works for you? If so, I'll mark it as complete.

I still don't know how to reliably reproduce this, because even if I remove the `display: block` again, it still works for me now. It's as if the display property of the sidebar keeps flip-flopping between inline and block. 🤔

**Comment by maxnersting** [comment]
Unfortunately, it still does not work as intended. At least, not for me.

**Comment by ranmaru22** [comment]
That's what I feared. I know what happens but it seems awfully random when and why ... 

Maybe it's really a Firefox bug with the current version and it'll get fixed upstream. Otherwise, if people who also experience this could chime in, it'd be much appreciated.

**Comment by Good-Janet** [comment]
I also ran into this! I was installing fresh from a Fedora 38 installation and was confused why it didn't match the screenshots and started playing around with the userChrome. Im not able to get it into the nice state from your screenshot unfortunately, and the newest pushed version also isn't working for me.

**Comment by KarimElsayad247** [comment]
Having the same issue. Most recent version didn't fix it. I can clearly see the `display: block !important;` in userChrome.css, but no dice.

**Comment by KarimElsayad247** [comment]
Ok, I think the problem is with the provided `tabCenterReborn.css`. Specifically, when one copies and pasted the whole file into the custom stylesheet textbox then clicks save Css, it's NOT SAVED. If you refresh the extension setting page, the textbox is emptied.

I guessed it might've been an error somewhere, so I copied and pasted chunk-by-chunk, saving at each point, and found that the issue is with this block

```css

/* If you want to disable the website previews,
comment out the @media line below and its closing bracket */
@media (max-width: 49px) {
    #tablist-wrapper:not(.shrinked) .tab-meta-image {
        background-color: inherit !important;
        border-width: 0 !important;
        box-shadow: none !important;
        height: 0 !important;
        width: 26px;
        margin-right: 0px;
    }
    #tablist-wrapper:not(.shrinked) .tab-icon-wrapper {
        background-color: transparent !important;
        margin-top: 0 !important;
        margin-left: 3px !important;
        box-shadow: none !important;
    }
    #tablist-wrapper:not(.shrinked) .tab-icon-overlay {
        bottom: 12px;
        left: 16px !important;
    }
}
```
