### ISSUE TITLE
Minimize, expand & close buttons disappeared in 123.0b1

### ISSUE THREAD

**Issue by UnholySheep** [ranmaru22/firefox-vertical-tabs#155]
I'm running Firefox Dev 123.0b1. It appears I can't minimize, expand or close with the buttons anymore, is this something on my end or a Mozilla issue?

![M8mcPJMTPf](https://github.com/ranmaru22/firefox-vertical-tabs/assets/115432589/8a418314-ca95-4e92-8421-597ef5e4ac62)

**Comment by ranmaru22** [comment]
If you're on Linux, this might be related to your GTK theme and the way it handles windows decorations. 

If you're on Windows, I can't really chime in because I don't use or know anything about it, but there it might be worth checking around in the settings if there exists an option related to window decorations there too. 

I could imagine Mozilla changing something around there, yes. They've done so in the past.

**Comment by Carighan** [comment]
If anyone finds a solution to this I'm all ear, just updated and I have the same issue.

**Comment by suhankins** [comment]
This worked for me
```css
#titlebar {
    z-index: 3;
}
```

**Comment by suhankins** [comment]
Probably a bandaid fix but works for me
```css
    .titlebar-buttonbox * {
        pointer-events: auto;
    }
    #titlebar {
        z-index: 3;
        pointer-events: none;
    }
```
