### ISSUE TITLE
Possible to stop the tab bar from collapsing?

### ISSUE THREAD

**Issue by martijnhopman** [ranmaru22/firefox-vertical-tabs#32]
Is there an 'option' in the custom CSS to stop the sidebar from collapsing?

So I can always have it in the collapsed mode (like how it is when hovering)

**Comment by ranmaru22** [comment]
Yes, just copy the settings from the `:hover` selectors on into the normal ones in both CSS files.

For example, the default has this:

```css
#sidebar-box[sidebarcommand*="tabcenter"]:not([hidden]) {
    display: block;
    position: absolute;
    min-width: 48px;
    max-width: 48px;
    overflow: hidden;
    transition: all 0.2s ease;
    border-right: 1px solid var(--sidebar-border-color);
    z-index: 1;
    top: 0;
    bottom: 0;
}

[sidebarcommand*="tabcenter"] #sidebar:hover,
#sidebar-box[sidebarcommand*="tabcenter"]:hover {
    min-width: 10vw !important;
    width: 30vw !important;
    max-width: 200px !important;
    z-index: 10 !important;
}
```

You would now replace all the values in the normal block with the values from the `:hover` block and then delete the `:hover` block. So it becomes:

```css
#sidebar-box[sidebarcommand*="tabcenter"]:not([hidden]) {
    display: block;
    position: absolute;
    min-width: 10vw !important;
    width: 30vw !important;
    max-width: 200px !important;
    overflow: hidden;
    transition: all 0.2s ease;
    border-right: 1px solid var(--sidebar-border-color);
    z-index: 10 !important;
    top: 0;
    bottom: 0;
}
```

If you do this with all blocks that have a `:hover` state, you have the expanded look all the time.

**Comment by XiCynx** [comment]
I've followed the instructions mentioned above to keep the tab bar from collapsing and that's worked successfully. But now the web page is hidden behind it. I think there is another piece of code that has to be edited, as before your theme is applied, the tab center stops the web page from going behind it and instead it stops where the tab bar starts.

![image](https://user-images.githubusercontent.com/20632191/186547379-fc304f6f-c3a5-4d84-9c8e-d9259e8f57d5.png)

**Comment by XiCynx** [comment]
Okay, it looks like I was able to fix the issue by messing around with some of the values.
This is what my code looks like in that area to get it to look like the screenshot below which I'm satisfied with.
The only thing that I'm not able to figure out currently, it how to hide this extra 48px bar that seems to be sticking out of the right side of the tab bar. Any thoughts on where this might be sitting in the css?

```css
/* General styles */
#browser {
    position: absolute;
}

#nav-bar, #urlbar {
    z-index: 100;
}

#sidebar-box:not([lwt-sidebar]){
    appearance: unset !important;
}

#sidebar-box[sidebarcommand*="tabcenter"] {
    z-index: 1;
}

#sidebar-box[sidebarcommand*="tabcenter"] #sidebar-header {
    visibility: collapse;
    display: none;
}

[sidebarcommand*="tabcenter"] #sidebar {
    min-width: 250px !important;
    max-width: 250px !important;
}

#sidebar-box[sidebarcommand*="tabcenter"]:not([hidden]) {
    display: block;
    position: relative;
    min-width: 1vw !important;
    width: 30vw !important;
    max-width: 250px !important;
    overflow: hidden;
    border-right: 1px solid var(--sidebar-border-color);
    z-index: 10 !important;
    top: 0;
    bottom: 0;
}
```

![image](https://user-images.githubusercontent.com/20632191/186548713-3cb3207d-ab67-424a-8dd1-dae74267c1ac.png)
