### ISSUE TITLE
[Win10] Graphics issues and fix

### ISSUE THREAD

**Issue by Perrelli9338** [ranmaru22/firefox-vertical-tabs#41]
Hola, I'm on **Firefox Dev Edition (104.0b6)**
### Issue
The toolbar is missing navigation buttons and the menu button is slightly shifted to the right as seen below:

![immagine](https://user-images.githubusercontent.com/99440016/183256342-dc112d0e-706a-4575-8ad0-5658af6d15b8.png)

### Solution
From:
```CSS
@media (-moz-platform: windows-win10) {
    :root[tabsintitlebar]{
        --uc-window-control-width: 105px; /* Old value */
    }

    #nav-bar{
        border-inline: var(--uc-window-drag-space-width,0px) /* Old value */ solid var(--toolbar-bgcolor) ; 
        ...
    }
   ...
}

```
to:
```CSS
@media (-moz-platform: windows-win10) {
    :root[tabsintitlebar]{
        --uc-window-control-width: 130px; /* New value */
    }

    #nav-bar{
        border-inline: var(--uc-window-drag-space-width,80px) /* New value */ solid var(--toolbar-bgcolor) ; 
        ...
    }
    ...
}
```
Result

![immagine](https://user-images.githubusercontent.com/99440016/183257013-5c1d44a5-19c7-4471-bc22-dafb7abb57d3.png)

> _Roger, over and out._
