### ISSUE TITLE
Still see tabs on fullscreen

### ISSUE THREAD

**Issue by Perrelli9338** [ranmaru22/firefox-vertical-tabs#47]
Hi, I see when webpage is in fullscreen the sidebar is not hidden.

### Issue
 
![immagine](https://user-images.githubusercontent.com/99440016/184972940-cc6cbe78-d735-47be-9532-72f0becc6763.png)

So to fix it at the end of the code on `userChrome.css` file I added this :
```CSS
@media all and (display-mode: fullscreen) {
    #sidebar-box[sidebarcommand*="tabcenter"]:not([hidden]) {
        min-width: 0px;
        max-width: 0px;
      }
    :root {
        --positionX1: 0px;
    }
  }
```

### Result
![immagine](https://user-images.githubusercontent.com/99440016/184973010-6e6a322a-ca00-4039-ab5a-58cbea19946e.png)
