### ISSUE TITLE
Extra padding covering screen on latest Nightly

### ISSUE THREAD

**Issue by mrBOIz** [ranmaru22/firefox-vertical-tabs#70]
Latest Firefox Nightly (107.0a1) introduced a new issue
There's some padding covering part of the screen
https://i.imgur.com/0fXTu7c.png

**Comment by ranmaru22** [comment]
Thanks for the heads up. Nightly is unsupported because it changes stuff all the time. If this is still a thing when 107 hits beta and dev channels, I'll take a look.

**Comment by mrBOIz** [comment]
thanks! 
i tried snoop the code and fix it but i guess i'll leave Tab Center deactivated for now

**Comment by Darkham42** [comment]
Same here, I fix it adding this in userChrome.css :
```
#sidebar-box {
    min-width: 4em !important;
}
```

**Comment by mrBOIz** [comment]
> Same here, I fix it adding this in userChrome.css :
> 
> ```
> #sidebar-box {
>     min-width: 4em !important;
> }
> ```

hmmm thanks but unfortunately it didn't work here... i made the padding smaller by changing your code from min to max-width, but it still didn't go away

**Comment by bmFtZQ** [comment]
I managed to fix it by replacing this rule in `userChrome.css`:

https://github.com/ranmaru22/firefox-vertical-tabs/blob/63cf63b2e887ebf0ce2d5143d478850e4afb5205/userChrome.css#L261-L264

with this:

```css
[sidebarcommand*="tabcenter"] #sidebar,
#sidebar-box[sidebarcommand*="tabcenter"] {
    min-width: 48px !important;
    max-width: 48px !important;
    width: 48px !important;
}
```
